# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

duos <- function(ys, MH_N = 20000L, k = 12L, alpha = 1) {
    .Call(`_BEDr_duos`, ys, MH_N, k, alpha)
}

rcpp_hello_world <- function() {
    .Call(`_BEDr_rcpp_hello_world`)
}

