# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title duos
#' @description
#' Modify a string in Rcpp.
#' @name duos
#' @param x a vector of strings
#' @examples
#' duos(x=c('Hello', "C++", 'header', 'files'))
#'
#' @export
duos <- function(y, MH_N = 20000L, k = 12L, alpha = 1) {
    .Call('_BEDr_duos', PACKAGE = 'BEDr', y, MH_N, k, alpha)
}

